# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='simple',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csimple.proto\x12\x06simple\"3\n\rSimpleRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"/\n\x0eSimpleResponse\x12\x0f\n\x07\x61vg_rtt\x18\x01 \x01(\x02\x12\x0c\n\x04time\x18\x02 \x01(\t2N\n\rSimpleService\x12=\n\nSimpleSend\x12\x15.simple.SimpleRequest\x1a\x16.simple.SimpleResponse\"\x00\x32\x62\n\x16ServerStreamingService\x12H\n\x13ServerStreamingSend\x12\x15.simple.SimpleRequest\x1a\x16.simple.SimpleResponse\"\x00\x30\x01\x62\x06proto3'
)




_SIMPLEREQUEST = _descriptor.Descriptor(
  name='SimpleRequest',
  full_name='simple.SimpleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='simple.SimpleRequest.destination', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='simple.SimpleRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=75,
)


_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='simple.SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avg_rtt', full_name='simple.SimpleResponse.avg_rtt', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='simple.SimpleResponse.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['SimpleRequest'] = _SIMPLEREQUEST
DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleRequest = _reflection.GeneratedProtocolMessageType('SimpleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEREQUEST,
  '__module__' : 'simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.SimpleRequest)
  })
_sym_db.RegisterMessage(SimpleRequest)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLERESPONSE,
  '__module__' : 'simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.SimpleResponse)
  })
_sym_db.RegisterMessage(SimpleResponse)



_SIMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SimpleService',
  full_name='simple.SimpleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=126,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='SimpleSend',
    full_name='simple.SimpleService.SimpleSend',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLESERVICE)

DESCRIPTOR.services_by_name['SimpleService'] = _SIMPLESERVICE


_SERVERSTREAMINGSERVICE = _descriptor.ServiceDescriptor(
  name='ServerStreamingService',
  full_name='simple.ServerStreamingService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=206,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServerStreamingSend',
    full_name='simple.ServerStreamingService.ServerStreamingSend',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERSTREAMINGSERVICE)

DESCRIPTOR.services_by_name['ServerStreamingService'] = _SERVERSTREAMINGSERVICE

# @@protoc_insertion_point(module_scope)
