# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_pb2 as simple__pb2


class SimpleServiceStub(object):
  """interface
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SimpleSend = channel.unary_unary(
        '/simple.SimpleService/SimpleSend',
        request_serializer=simple__pb2.SimpleRequest.SerializeToString,
        response_deserializer=simple__pb2.SimpleResponse.FromString,
        )


class SimpleServiceServicer(object):
  """interface
  """

  def SimpleSend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimpleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SimpleSend': grpc.unary_unary_rpc_method_handler(
          servicer.SimpleSend,
          request_deserializer=simple__pb2.SimpleRequest.FromString,
          response_serializer=simple__pb2.SimpleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simple.SimpleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ServerStreamingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ServerStreamingSend = channel.unary_stream(
        '/simple.ServerStreamingService/ServerStreamingSend',
        request_serializer=simple__pb2.SimpleRequest.SerializeToString,
        response_deserializer=simple__pb2.SimpleResponse.FromString,
        )


class ServerStreamingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ServerStreamingSend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerStreamingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ServerStreamingSend': grpc.unary_stream_rpc_method_handler(
          servicer.ServerStreamingSend,
          request_deserializer=simple__pb2.SimpleRequest.FromString,
          response_serializer=simple__pb2.SimpleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simple.ServerStreamingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
